import 'package:dth/screens/recycle/widgets/rclboxdrill.dart';
import 'package:dth/widgets/headertext.dart';
import 'package:dth/widgets/textfield.dart';
import 'package:dth/widgets/textformfield.dart';
import 'package:flutter/material.dart';

class RecycleAddScreen extends StatefulWidget {
  const RecycleAddScreen({super.key});

  @override
  State<RecycleAddScreen> createState() => _RecycleAddScreenState();
}

class _RecycleAddScreenState extends State<RecycleAddScreen> {
  final TextEditingController _weightController=TextEditingController();
  @override
  Widget build(BuildContext context) {
    return Container(
       decoration: BoxDecoration(
     image: DecorationImage(image: AssetImage('assets/images/bg.jpg'),fit: BoxFit.cover)
    ),
      child: Scaffold(
          appBar: AppBar(
            elevation: 0,
            backgroundColor: Colors.transparent,
            title: Container(
                alignment: Alignment.center,
                padding: EdgeInsets.only(right: 45),
                height: 40,
                child:
                    Image.asset('assets/images/appbar.jpg', fit: BoxFit.cover)),
            leading: IconButton(
                onPressed: () {
                  Navigator.pop(context);
                },
                icon: Icon(
                  Icons.arrow_back_ios_new_rounded,
                  color: Colors.black,
                ))),
        backgroundColor: Colors.transparent,
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              Row(
                children: [
                  Text('Batch No:  ',style: headerText(),),
                  Text('"Generated By system"',style: labelText(),)
                ],
              ),
              SizedBox(height: 20,),
              Row(mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Container(
                              padding: EdgeInsets.all(5),
                              alignment: Alignment.center,
                              height: 120,
                              width: 120,
                              decoration: BoxDecoration(
                                  color: Colors.grey,
                                  borderRadius: BorderRadius.circular(8)),
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Icon(Icons.camera_alt_outlined),
                                  Text(
                                      'OPEN CAMERA  - BOX WITH MATERIAL '),
                                     
                                ],
                              ),
                            ),
                     Container(padding: EdgeInsets.only(right: 10),
                      height: 30,
                      width: 120,
                      decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(15),
                          border: Border.all(color: Colors.transparent)),
                      child: Center(
                        child: TextField(textAlign: TextAlign.center,
                          controller: _weightController,
                          style: TextStyle(
                              fontSize: 16,
                              color: Colors.black,
                              fontWeight: FontWeight.w400),
                          decoration: InputDecoration(
                            focusedBorder: InputBorder.none,
                          ),
                        ),
                      ),
                    ),

                ],
              ),
              SizedBox(height: 20,),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                Text('Box No:',style: headerText(),),
                RecycleBoxDropdownWidget()
              ],),
              SizedBox(height: 10,),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Material Qty:',style: headerText(),),
                  Text('"Calculated Quantity"',style: labelText(),)
                ],
              ),
              SizedBox(height: 30,),

              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('State',style: headerText(),),
                  Text('To Recycle',style: labelText(),)
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}